:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\FactsetEstimatesApi
dotnet build src\FactsetEstimatesApi
echo Now, run the following to start the project: dotnet run -p src\FactsetEstimatesApi\FactsetEstimatesApi.csproj --launch-profile web.
echo.
